name: account_ledger_library
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.3.0-238.0.dev <4.0.0'

dependencies:
  integer: ^2.0.1
  intl: ^0.19.0
  tuple: ^2.0.2
  os_detect: ^2.0.1
  http: ^1.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
